trigger: none

variables:
  environment: devtest   #<< change this for every environment
  openshiftService: devops-toolchain  #<< change this for every environment
  KubeHttpCacheConfigName: 'kube-httpcache'
  openshiftProject: 'devops-toolchain'
  ocVersion: 'v4.13.44'
  kubeHttpCacheVersion: '0.1'

stages:
  - stage: build_kube-httpcache
    displayName: 'Build KubeHttpCache Image'
    dependsOn: [] 
    jobs:
      - template: templates/build-kube-httpcache.yml
        parameters:
          environment: $(environment)
          openshiftService: $(openshiftService)
          namespace: $(openshiftProject)
          ocVersion: $(ocVersion)
          KubeHttpCacheConfigName: $(KubeHttpCacheConfigName)
          kubeHttpCacheVersion: $(kubeHttpCacheVersion)