trigger: none
pr: none

variables:
  environment: devtest   
  openshiftService: devops-toolchain
  KubeHttpCacheConfigName: 'kube-httpcache'
  openshiftProject: 'devops-toolchain'
  ocVersion: 'v4.13.44'
  kubeHttpCacheVersion: 'stable-2.0'
  sonarQubeConnection: 'sonarcloud'
  goVersion: '1.24.6'  
  # docker variables below
  goToolsetTag: '1.24.6-1760420453'         # <-- latest UBI 9 gotoolset image tag as of 20-10-2025 -- https://catalog.redhat.com/en/software/containers/rhel9/go-toolset/61df08166d9a1b7b2aab2344
  ubiTag: '9.6-1760340943'                    # <-- latest UBI 9 core image tag as of 20-10-2025 -- https://catalog.redhat.com/en/software/containers/ubi9/ubi/615bcf606feffc5384e8452e
  promExporterVersion: 'v1.7.0'
  varnishRepoVersion: '80'                  # <-- https://packagecloud.io/varnishcache/  repo version from here
  varnishVersion: '8.0.0'                   # <-- https://packagecloud.io/varnishcache/  varnish version from here
  varishRelease: '1'                        # <-- https://packagecloud.io/varnishcache/  varnish release number from here
  varnishArch: 'el9.x86_64'                 # <-- https://packagecloud.io/varnishcache/  varnish architecture from here
stages:
  - stage: GoVulnCheck
    displayName: 'Go Vulnerability Scan'
    jobs:
      - job: VulnScan
        displayName: 'Run govulncheck'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - task: GoTool@0
          inputs:
            version: $(goVersion)
          
        - script: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go install golang.org/x/vuln/cmd/govulncheck@latest
            govulncheck ./...
          displayName: 'Install govulncheck and scan'
  - stage: SonarQube_Analysis
    displayName: 'SonarQube Analysis'
    dependsOn: GoVulnCheck
    jobs:
        - job: SonarQube
          displayName: 'Run SonarQube Scanner'
          steps:
            - task: SonarCloudPrepare@3
              inputs:
                SonarQube: $(sonarQubeConnection)
                organization: 'city-of-helsinki'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: 'kube-httpcache'
                cliProjectName: 'kube-httpcache'
                cliSources: '.'
            - task: SonarCloudAnalyze@3
            - task: SonarCloudPublish@3
              inputs:
                pollingTimeoutSec: '300'
                failWhenQualityGateFails: true
  - stage: build_kube_httpcache
    displayName: 'Build KubeHttpCache Image'
    dependsOn: SonarQube_Analysis
    condition: succeeded()
    jobs:
      - template: templates/build-kube-httpcache.yml
        parameters:
          environment: $(environment)
          openshiftService: $(openshiftService)
          namespace: $(openshiftProject)
          ocVersion: $(ocVersion)
          KubeHttpCacheConfigName: $(KubeHttpCacheConfigName)
          kubeHttpCacheVersion: $(kubeHttpCacheVersion)
          ubiTag: $(ubiTag)
          goToolsetTag: $(goToolsetTag)
          promExporterVersion: $(promExporterVersion)
          varnishRepoVersion: $(varnishRepoVersion)
          varnishVersion: $(varnishVersion)
          varishRelease: $(varishRelease)
          varnishArch: $(varnishArch)