trigger: none
pr: none

variables:
  environment: devtest   #<< change this for every environment
  openshiftService: devops-toolchain  #<< change this for every environment
  KubeHttpCacheConfigName: 'kube-httpcache'
  openshiftProject: 'devops-toolchain'
  ocVersion: 'v4.13.44'
  kubeHttpCacheVersion: '0.2'
  sonarQubeConnection: 'sonarcloud'
  goVersion: '1.24.2'  
  goInstallPath: '/usr/local/go'
  govulncheckVersion: 'latest'

stages:
  - stage: GoVulnCheck
    displayName: 'Go Vulnerability Scan'
    jobs:
      - job: VulnScan
        displayName: 'Run govulncheck'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
        - script: |
            echo "Installing Go version $(goVersion)..."
            
            # Download Go tarball to the /tmp directory to avoid permission issues
            wget https://golang.org/dl/go$(goVersion).linux-amd64.tar.gz -P /tmp/
            
            # Extract Go tarball into /usr/local
            sudo tar -C /usr/local -xzf /tmp/go$(goVersion).linux-amd64.tar.gz
            
            # Ensure the Go binary is in the system PATH
            echo "export PATH=$PATH:/usr/local/go/bin" >> $BASH_ENV
            source $BASH_ENV
            
            # Verify Go is installed correctly
            go version
          displayName: 'Install Go $(goVersion)'
        
        - script: |
            source $BASH_ENV
            echo "Installing govulncheck version $(govulncheckVersion)..."
            /usr/local/go/bin/go install golang.org/x/vuln/cmd/govulncheck@$(govulncheckVersion)
            echo "govulncheck installed at: $(which govulncheck)"
            govulncheck ./...
          displayName: 'Run govulncheck'
  - stage: SonarQube_Analysis
    displayName: 'SonarQube Analysis'
    dependsOn: GoVulnCheck
    jobs:
        - job: SonarQube
          displayName: 'Run SonarQube Scanner'
          steps:
            - task: SonarCloudPrepare@3
              inputs:
                SonarQube: $(sonarQubeConnection)
                organization: 'city-of-helsinki'
                scannerMode: 'CLI'
                configMode: 'manual'
                cliProjectKey: 'kube-httpcache'
                cliProjectName: 'kube-httpcache'
                cliSources: '.'
            - task: SonarCloudAnalyze@3
            - task: SonarCloudPublish@3
              inputs:
                pollingTimeoutSec: '300'
  - stage: build_kube_httpcache
    displayName: 'Build KubeHttpCache Image'
    dependsOn: SonarQube_Analysis
    jobs:
      - template: templates/build-kube-httpcache.yml
        parameters:
          environment: $(environment)
          openshiftService: $(openshiftService)
          namespace: $(openshiftProject)
          ocVersion: $(ocVersion)
          KubeHttpCacheConfigName: $(KubeHttpCacheConfigName)
          kubeHttpCacheVersion: $(kubeHttpCacheVersion)