parameters:
- name: environment
  type: string
- name: openshiftService
  type: string
- name: namespace
  type: string
- name: KubeHttpCacheConfigName
  type: string
- name: ocVersion
  type: string
- name: kubeHttpCacheVersion
  type: string
- name: goToolsetTag
  type: string
- name: ubiTag
  type: string
- name: promExporterVersion
  type: string
- name: varnishRepoVersion
  type: string
- name: varnishVersion
  type: string
- name: varishRelease
  type: string
- name: varnishArch
  type: string

jobs:
  - job: BuildDockerImage
    displayName: 'Build KubeHttpCache Image'
    pool: Default
    steps:
      - task: oc-setup@2
        displayName: 'Setup OpenShift CLI'
        inputs:
          connectionType: 'OpenShift Connection Service'
          openshiftService: ${{ parameters.openshiftService }}
          version: ${{ parameters.ocVersion }}
      - script: |
          envsubst < "$(Build.SourcesDirectory)/build/package/docker/Dockerfile" > tempdockerfile && mv tempdockerfile "$(Build.SourcesDirectory)/build/package/docker/Dockerfile"
          cat "$(Build.SourcesDirectory)/build/package/docker/Dockerfile"

          CONFIG_FILE="$(Build.SourcesDirectory)/build/package/docker/${CONFIG_NAME}-build-config.yaml"

          envsubst < "$CONFIG_FILE" > temp.yaml && mv temp.yaml "$CONFIG_FILE"

          cat "$CONFIG_FILE"

          oc apply -f "$CONFIG_FILE" -n "$NAMESPACE"

          oc start-build "$CONFIG_NAME" --from-dir="$(Build.SourcesDirectory)" -n "$NAMESPACE" --insecure-skip-tls-verify=true
          
          echo "Waiting for build to be created..."
          while true; do
            build_name=$(oc get builds -n "$NAMESPACE" --selector=openshift.io/build-config.name="$CONFIG_NAME" --sort-by=.metadata.creationTimestamp -o jsonpath='{.items[-1].metadata.name}')
            if [ -n "$build_name" ]; then
              echo "Latest build name: $build_name"
              break
            fi
            echo "Build not found. Retrying in 10 seconds..."
            sleep 10
          done

          echo "Monitoring build status..."
          while true; do
            buildStatus=$(oc get build "$build_name" -n "$NAMESPACE" -o jsonpath='{.status.phase}')
            echo "Build status: $buildStatus"
            if [ "$buildStatus" == "Complete" ]; then
              echo "Build succeeded with status: $buildStatus"
              break
            elif [ "$buildStatus" == "Failed" ] || [ "$buildStatus" == "Error" ]; then
              echo "Build failed with status: $buildStatus"
              exit 1
            fi
            sleep 10
          done

          oc logs "build/$build_name" -n "$NAMESPACE"
        displayName: 'Apply BuildConfig and Start Build'
        env:
          ENVIRONMENT: ${{ parameters.environment }}
          NAMESPACE: ${{ parameters.namespace }}
          CONFIG_NAME: ${{ parameters.KubeHttpCacheConfigName }}
          KUBE_HTTP_CACHE_VERSION: ${{ parameters.kubeHttpCacheVersion }}
          __GO_VERSION__: ${{ parameters.goToolsetTag }}
          __UBI_TAG__: ${{ parameters.ubiTag }}
          PROM_EXPORTER_VERSION: ${{ parameters.promExporterVersion }}
          VARNISH_REPO_VERSION: ${{ parameters.varnishRepoVersion }}
          VARNISH_VERSION: ${{ parameters.varnishVersion }}
          VARNISH_RELEASE: ${{ parameters.varishRelease }}
          VARNISH_ARCH: ${{ parameters.varnishArch }}