name: Test

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  verify_helm:
    name: Verify Helm chart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        helm: [ '3.1.2' ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@b7246d12e77f0c8028d6728cf555a576ad375c2d
        with:
          version: "v${{ matrix.helm }}"
      - name: Test template rendering
        run: helm template ./chart/.

      - name: Lint chart
        run: helm lint ./chart/

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.26.5"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: "0.181.1"
          args: release -f build/ci/.goreleaser.yml --snapshot --skip-publish --rm-dist
